apiVersion: v1
kind: Config
clusters:
- name: dev
  cluster:
    server: https://master.kubernetes.com:6443
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    user: kubelet
contexts:
- context:
    cluster: dev
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
users:
- name: kubelet
  user:
    client-key: /etc/kubernetes/ssl/kubelet-client-key.pem
    client-certificate: /etc/kubernetes/ssl/kubelet-client.pem
