apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://master.kubernetes.com:6443
    certificate-authority: /srv/kubernetes/ssl/ca.pem
    client-key: /srv/kubernetes/ssl/kubelet-client.pem
    client-certificate: /srv/kubernetes/ssl/kubelet-client-key.pem
    user: kubelet
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
users:
- name: kubelet
  user:
    token: fcpbN76HNF542pY4i1vWXpVbZZ43J1jU
